// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PCode.Api.Infrastructure;
using System;

namespace PCode.Api.Migrations
{
    [DbContext(typeof(MainDatabaseContext))]
    [Migration("20180209140752_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PCode.Domain.Profile", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Level");

                    b.Property<string>("Title");

                    b.HasKey("Guid");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("PCode.Domain.Skill", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<Guid?>("ProfileGuid");

                    b.Property<string>("Score");

                    b.HasKey("Guid");

                    b.HasIndex("ProfileGuid");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("PCode.Domain.Skill", b =>
                {
                    b.HasOne("PCode.Domain.Profile")
                        .WithMany("Skills")
                        .HasForeignKey("ProfileGuid");
                });
#pragma warning restore 612, 618
        }
    }
}
